GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1vb25leWJyYXNrYXdhbG92aWNoIiwiZW1haWwiOiJtb29uZXlicmFza2F3YWxvdmljaEBwbS5tZSIsImlhdCI6MTY1OTU1MDE0OH0.JFnC21nx0AizsJXChKacgrSe0Mm0cDETUatN68LghAQ


###

POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "mooneybraskawalovich",
    "email": "mooneybraskawalovich@pm.me"
}
